import { StyleSheet, Dimensions } from "react-native";
import { COLORS } from "../../constants/colors";

const { width } = Dimensions.get("window");
const CARD_WIDTH = width - 40;
const CARD_HEIGHT = CARD_WIDTH * 0.69;

export const styles = StyleSheet.create({
  container: {
    padding: 20,
    backgroundColor: COLORS.background,
  },
  cardContainer: {
    height: CARD_HEIGHT,
    marginBottom: 20,
    // Add perspective for 3D effect
    transform: [{ perspective: 1000 }],
  },
  cardFace: {
    position: "absolute",
    width: CARD_WIDTH,
    height: CARD_HEIGHT,
    borderRadius: 20,
    shadowColor: COLORS.shadow,
    shadowOffset: {
      width: 0,
      height: 12,
    },
    shadowOpacity: 0.2,
    shadowRadius: 16,
    elevation: 12,
    // Ensure proper 3D rendering
    backfaceVisibility: 'hidden',
  },

  gradientBackground: {
    flex: 1,
    backgroundColor: COLORS.primary,
    borderRadius: 20,
    padding: 24,
    position: "relative",
    overflow: "hidden",
  },
  gradientBackgroundBack: {
    flex: 1,
    backgroundColor: COLORS.secondary || "#4338ca", // Use COLORS.secondary or define in constants
    borderRadius: 20,
    position: "relative",
    overflow: "hidden",
  },
  cardTop: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: 24,
  },
  topLeft: {
    flexDirection: "row",
    alignItems: "center",
  },
  wifiIcon: {
    transform: [{ rotate: "90deg" }],
    marginRight: 12,
    opacity: 0.8,
  },
  chipContainer: {
    width: 52,
    height: 36,
    backgroundColor: "#fbbf24",
    borderRadius: 8,
    justifyContent: "center",
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  chip: {
    width: 28,
    height: 20,
    backgroundColor: "#92400e",
    borderRadius: 3,
  },
  topRight: {
    alignItems: "flex-end",
  },
  bankName: {
    fontSize: 13,
    color: COLORS.white,
    opacity: 0.9,
    marginBottom: 4,
    fontWeight: "500",
  },
  cardType: {
    fontSize: 22,
    fontWeight: "bold",
    color: COLORS.white,
    letterSpacing: 2,
  },
  cardNumberContainer: {
    marginBottom: 44,
    alignItems: "center",
    marginVertical: 20,
  },
  cardNumber: {
    fontSize: 22,
    fontFamily: "monospace", 
    color: COLORS.white,
    letterSpacing: 3,
    textAlign: "center",
    fontWeight: "600",
  },
  cardBottom: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-end",
    marginBottom: 16,
  },
  cardHolderSection: {
    flex: 1,
  },
  expirySection: {
    alignItems: "flex-end",
  },
  label: {
    fontSize: 11,
    color: COLORS.white,
    opacity: 0.8,
    marginBottom: 4,
    letterSpacing: 1.2,
    fontWeight: "500",
  },
  cardHolderName: {
    fontSize: 16,
    fontWeight: "600",
    color: COLORS.white,
    letterSpacing: 1.5,
  },
  expiryDate: {
    fontSize: 16,
    fontWeight: "600",
    color: COLORS.white,
    letterSpacing: 1.5,
  },
  balanceContainer: {
    alignItems: "center",
    marginTop: 8,
  },
  balanceLabel: {
    fontSize: 12, // Increased for better accessibility
    color: COLORS.white,
    opacity: 0.7,
    marginBottom: 4,
    letterSpacing: 1,
  },
  balanceAmount: {
    fontSize: 18,
    fontWeight: "bold",
    color: COLORS.white,
    letterSpacing: 1,
  },
  decorativeCircle1: {
    position: "absolute",
    top: -20,
    right: -20,
    width: 100,
    height: 100,
    borderRadius: 50,
    backgroundColor: COLORS.white,
    opacity: 0.05,
  },
  decorativeCircle2: {
    position: "absolute",
    bottom: -30,
    left: -30,
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: COLORS.white,
    opacity: 0.05,
  },
  decorativeLine: {
    position: "absolute",
    top: "50%",
    left: 0,
    right: 0,
    height: 1,
    backgroundColor: COLORS.white,
    opacity: 0.1,
  },
  // Back side styles
  magneticStrip: {
    width: "100%",
    height: 50,
    backgroundColor: "#000",
    marginTop: 25,
  },
  backContent: {
    padding: 24,
    flex: 1,
  },
  signatureStrip: {
    width: "100%",
    height: 42,
    backgroundColor: "#e5e5e5",
    borderRadius: 6,
    marginBottom: 10,
    justifyContent: "center",
    alignItems: "flex-end",
    paddingRight: 12,
  },
  cvvContainer: {
    backgroundColor: COLORS.white,
    paddingHorizontal: 14,
    paddingVertical: 4,
    borderRadius: 4,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 1,
  },
  cvvText: {
    fontSize: 15,
    fontWeight: "bold",
    color: "#000",
    fontFamily: "monospace", 
  },
  signatureLabel: {
    fontSize: 11,
    color: COLORS.white,
    opacity: 0.8,
    marginBottom: 24,
    fontWeight: "500",
  },
  customerServiceInfo: {
    marginBottom: 20,
  },
  customerServiceText: {
    fontSize: 12,
    color: COLORS.white,
    opacity: 0.85,
    marginBottom: 2,
    fontWeight: "500",
  },
  termsText: {
    fontSize: 10,
    color: COLORS.white,
    opacity: 0.7,
    lineHeight: 16,
    marginTop: 10,
  },
  backBranding: {
    position: "absolute",
    bottom: 24,
    right: 24,
    alignItems: "flex-end",
  },
  backBankName: {
    fontSize: 11,
    color: COLORS.white,
    opacity: 0.7,
    marginBottom: 2,
  },
  backCardType: {
    fontSize: 18,
    fontWeight: "bold",
    color: COLORS.white,
  },
  // Info card styles
  infoCard: {
    backgroundColor: COLORS.card,
    borderRadius: 20,
    padding: 24,
    marginBottom: 16,
    shadowColor: COLORS.shadow,
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 4,
  },
  infoHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 20,
  },
  infoTitle: {
    fontSize: 20,
    fontWeight: "700",
    color: COLORS.text,
    marginLeft: 8,
  },
  infoGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
  },
  infoItem: {
    width: "50%",
    marginBottom: 16,
  },
  infoLabel: {
    fontSize: 14,
    color: COLORS.textLight,
    marginBottom: 4,
    fontWeight: "500",
  },
  infoValue: {
    fontSize: 16,
    fontWeight: "600",
    color: COLORS.text,
  },
  statusActive: {
    color: "#10b981",
  },
  controlPanel: {
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 12,
  },
  flipButton: {
    backgroundColor: COLORS.primary,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 14,
    paddingHorizontal: 24,
    borderRadius: 28,
    shadowColor: COLORS.primary,
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 4,
    flex: 1,
  },
  flipButtonText: {
    color: COLORS.white,
    fontSize: 16,
    fontWeight: "600",
    marginLeft: 8,
  },
  secondaryButton: {
    backgroundColor: COLORS.card,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 14,
    paddingHorizontal: 24,
    borderRadius: 28,
    borderWidth: 1,
    borderColor: COLORS.border,
    flex: 1,
  },
  secondaryButtonText: {
    color: COLORS.primary,
    fontSize: 16,
    fontWeight: "600",
    marginLeft: 8,
  },
});